name: 'JSON Comparison Workflow'
description: 'Compares JSON files from a folder with remote URLs and sends Slack notifications on differences'
author: 'JSON Comparison Team'
branding:
  icon: 'git-compare'
  color: 'green'

inputs:
  # Required: Folder path to scan for JSON files
  folder-path:
    description: 'Path to the folder containing JSON files to compare (e.g., config/, data/)'
    required: true
    default: 'config'
  
  # Required: Base URL for remote JSON files
  base-url:
    description: 'Base URL for remote JSON files (e.g., https://api.example.com/config)'
    required: true
  
  # Optional: Slack webhook URL (if not provided, workflow will handle notifications)
  slack-webhook-url:
    description: 'Slack webhook URL for notifications (optional - workflow can handle notifications)'
    required: false
  
  # Optional: Slack channel override
  slack-channel:
    description: 'Slack channel to send notifications to (overrides webhook default)'
    required: false
  
  # Optional: Comparison mode
  comparison-mode:
    description: 'Comparison mode (strict|lenient)'
    required: false
    default: 'strict'
  
  # Optional: Ignore specific keys during comparison
  ignore-keys:
    description: 'Comma-separated list of keys to ignore during comparison'
    required: false
    default: ''
  
  # Optional: File extensions to include
  file-extensions:
    description: 'Comma-separated file extensions to include (e.g., json,jsonc)'
    required: false
    default: 'json'
  
  # Optional: Recursive folder scanning
  recursive:
    description: 'Scan subfolders recursively'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'
