name: ICS JSON Comparison Workflow

on:
  workflow_dispatch:
    inputs:
      folder_path:
        description: 'Folder path to scan for JSON files'
        required: true
        default: 'config'
        type: string
      base_url:
        description: 'Base URL for remote JSON files'
        required: true
        default: 'https://api.example.com/config'
        type: string
      comparison_mode:
        description: 'Comparison mode (strict|lenient)'
        required: true
        default: 'strict'
        type: choice
        options:
          - strict
          - lenient
      ignore_keys:
        description: 'Comma-separated keys to ignore during comparison'
        required: false
        default: ''
        type: string
      file_extensions:
        description: 'Comma-separated file extensions to include'
        required: false
        default: 'json'
        type: string
      recursive:
        description: 'Scan subfolders recursively'
        required: false
        default: 'false'
        type: boolean
      slack_channel:
        description: 'Slack channel to send notifications (default #json-comparison)'
        required: true
        default: 'C03SA9S4A4X'
        type: string
      runs:
        description: 'Specify the number of parallel comparison runs (default - 1)'
        required: false
        default: 1
        type: number

defaults:
  run:
    shell: bash

jobs:
  input_logger:
    runs-on: aexp-ubuntu-latest-small
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: ðŸ“ Set matrix
        id: set-matrix
        run: |
          runs=${{ github.event.inputs.runs}}
          arr=$(seq 1 $runs | jq -R . | jq -s | jq -c .)
          echo "matrix=$arr" >> $GITHUB_OUTPUT

      - name: âœï¸ Log Inputs
        id: inputs_logged
        run: |
          echo "### âœ… Logging inputs for JSON Comparison workflow:
          - **Folder Path:** ${{ github.event.inputs.folder_path }}
          - **Base URL:** ${{ github.event.inputs.base_url }}
          - **Comparison Mode:** ${{ github.event.inputs.comparison_mode }}
          - **File Extensions:** ${{ github.event.inputs.file_extensions }}
          - **Recursive:** ${{ github.event.inputs.recursive }}
          - **RunAt:** $(date)
          - **Runs:** ${{ github.event.inputs.runs }}" >> $GITHUB_STEP_SUMMARY

  json-comparison:
    runs-on: aexp-ubuntu-latest-medium
    needs: input_logger
    if: ${{ github.event.inputs.folder_path != '' && github.event.inputs.base_url != '' }}
    name: JSON Comparison for ${{ github.event.inputs.folder_path }} - ${{ github.event.inputs.base_url }}
    env:
      NODE_ENV: production
    strategy:
      matrix:
        run: ${{ fromJson(needs.input_logger.outputs.matrix) }}
    steps:
      - name: ðŸš§ Checkout code
        uses: amex-ghactions/checkout@v4.1.0

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: ðŸ”— Install dependencies
        run: |
          npm ci --ignore-scripts
          npm install @actions/core @actions/github @actions/exec @slack/web-api deep-diff
          npm install -g @vercel/ncc

      - name: ðŸ—ï¸ Build JSON Comparison Action
        run: |
          cd json-comparison-workflow
          npm install
          ncc build src/index.js -o dist

      - name: ðŸ” Run JSON Comparison
        id: run_comparison
        run: |
          echo "startedAt=$(date)" >> $GITHUB_OUTPUT
          cd json-comparison-workflow
          node dist/index.js \
            --folder-path "${{ github.event.inputs.folder_path }}" \
            --base-url "${{ github.event.inputs.base_url }}" \
            --slack-channel "${{ github.event.inputs.slack_channel }}" \
            --comparison-mode "${{ github.event.inputs.comparison_mode }}" \
            --ignore-keys "${{ github.event.inputs.ignore_keys }}" \
            --file-extensions "${{ github.event.inputs.file_extensions }}" \
            --recursive "${{ github.event.inputs.recursive }}"
        continue-on-error: true

      - name: ðŸ“Š Generate HTML Report
        if: ${{ success() }}
        id: generate_html_report
        run: |
          echo "Generating HTML report for JSON comparison results..."
          # The report is automatically generated by the comparison action
          echo "Report generated in reports/ directory"
          echo "see report here: https://github.aexp.com/pages/amex-eng/json-validator/reports/" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

      - name: Create branch name
        id: branch_name
        run: echo "BRANCH_NAME=json-comparison-report-$(printf "%07d" ${{ github.run_number }})" >> $GITHUB_ENV

      - name: Deploy HTML Reports to GitHub Pages ðŸš€
        if: ${{ success() }}
        uses: amex-ghactions/github-pages-deploy-action@v4.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: reports # Deploy the reports folder with HTML files.
          CLEAN: true
          TARGET-FOLDER: reports
        continue-on-error: true

      - name: Commit and push changes
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b ${{ env.BRANCH_NAME}}
          git add reports/
          git commit -m "chore(reports): add html report for ${{ github.event.inputs.folder_path }} - ${{ github.event.inputs.base_url }}"
          git push origin ${{ env.BRANCH_NAME}}
          echo "PR_NUMBER=$(git rev-parse --short HEAD)"

      - name: Create a PR
        if: ${{ success() }}
        uses: amex-ghactions/create-pull-request-action@baf0e1e39d354d2468900d2b9c15f1045a252718
        id: create-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: ${{ env.BRANCH_NAME}}
          to-branch: develop
          title: 'chore(reports): add html report for ${{ github.event.inputs.folder_path }} - ${{ github.event.inputs.base_url }}'
          body: 'In this PR we are adding the HTML report for the JSON comparison workflow.'
          repository-owner: amex-eng
          repository: ${{ github.event.repository.name }}

      - name: ðŸ”” Slack Alert - Success
        if: ${{ success() }}
        uses: amex-eng/github-actions-slack@v1.1.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ github.event.inputs.slack_channel }}
          slack-text: |
            :white_check_mark: *JSON Comparison Summary*
            *Comparison Status:* COMPLETED
            *Folder Path:* `${{ github.event.inputs.folder_path }}`
            *Base URL:* `${{ github.event.inputs.base_url }}`
            *Comparison Mode:* `${{ github.event.inputs.comparison_mode }}`
            *Date & Time:* `${{ steps.run_comparison.outputs.startedAt }}`
            *Report:* <https://github.aexp.com/pages/amex-eng/json-validator/reports/|Click here to view the full report>
            *Report Link:* https://github.aexp.com/pages/amex-eng/json-validator/reports/
            _For Developers_
            *Branch:* `${{ env.BRANCH_NAME }}`
            *Report PR:* <https://github.aexp.com/${{ github.repository }}/pull/${{ steps.create-pr.outputs.pull_number }}|#${{ steps.create-pr.outputs.pull_number }}>
            If you have questions, reply in this channel or contact the JSON Comparison team.

      - name: ðŸ”” Slack Alert - Failure
        if: ${{ failure() }}
        uses: amex-eng/github-actions-slack@v1.1.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ github.event.inputs.slack_channel }}
          slack-text: |
            :x: *JSON Comparison Summary*
            *Comparison Status:* FAILED
            *Folder Path:* `${{ github.event.inputs.folder_path }}`
            *Base URL:* `${{ github.event.inputs.base_url }}`
            *Comparison Mode:* `${{ github.event.inputs.comparison_mode }}`
            *Date & Time:* `${{ steps.run_comparison.outputs.startedAt }}`
            *Job ID:* `${{ github.run_id }}`
            *Report:* <https://github.aexp.com/pages/amex-eng/json-validator/reports/|Click here to view the full report>
            *Report Link:* https://github.aexp.com/pages/amex-eng/json-validator/reports/
            Please check the report or contact the JSON Comparison team for details.
