name: JSON Comparison Scheduler

on:
  # Run on a schedule (every day at 9 AM UTC)
  schedule:
    - cron: '0 9 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      folder_path:
        description: 'Folder path to scan for JSON files'
        required: true
        default: 'config'
        type: string
      base_url:
        description: 'Base URL for remote JSON files'
        required: true
        default: 'https://api.example.com/config'
        type: string
      comparison_mode:
        description: 'Comparison mode (strict|lenient)'
        required: false
        default: 'strict'
        type: choice
        options:
          - strict
          - lenient
      ignore_keys:
        description: 'Comma-separated keys to ignore during comparison'
        required: false
        default: ''
        type: string
      file_extensions:
        description: 'Comma-separated file extensions to include'
        required: false
        default: 'json'
        type: string
      recursive:
        description: 'Scan subfolders recursively'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read
  actions: read

jobs:
  compare-json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install @actions/core @actions/github @actions/exec @slack/web-api deep-diff
          npm install -g @vercel/ncc
      
      - name: Build action
        run: |
          ncc build src/index.js -o dist
      
      - name: JSON Comparison
        uses: ./
        with:
          folder-path: ${{ github.event.inputs.folder_path || 'config' }}
          base-url: ${{ github.event.inputs.base_url || 'https://api.example.com/config' }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          comparison-mode: ${{ github.event.inputs.comparison_mode || 'strict' }}
          ignore-keys: ${{ github.event.inputs.ignore_keys || '' }}
          file-extensions: ${{ github.event.inputs.file_extensions || 'json' }}
          recursive: ${{ github.event.inputs.recursive || 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
